// Copyright 2026 WBR IP & License Holding Pte. Ltd.
// SPDX-License-Identifier: Apache-2.0

package bundle

import (
	"crypto/sha256"
	"encoding/hex"
	"math"
	"strings"
	"testing"
)

// Hard-Gate R9 — byte-exact reference vectors generated by hand against
// the Python forensicdata_audit.canonical.canonical_json semantics.
// Each pair is (input, expected-canonical-JSON-string). The Go output
// MUST match the Python output byte-for-byte.
var canonicalGoldenVectors = []struct {
	name      string
	input     any
	canonical string
}{
	// Primitives
	{"null", nil, "null"},
	{"true", true, "true"},
	{"false", false, "false"},
	{"int_zero", 0, "0"},
	{"int_positive", 42, "42"},
	{"int_negative", -7, "-7"},
	{"int_large", int64(1745000000000), "1745000000000"},

	// Empty containers
	{"empty_object", map[string]any{}, "{}"},
	{"empty_array", []any{}, "[]"},

	// Strings
	{"empty_string", "", `""`},
	{"plain_ascii", "hello", `"hello"`},
	{"escape_dquote", `say "hi"`, `"say \"hi\""`},
	{"escape_backslash", `path\to\file`, `"path\\to\\file"`},
	{"escape_newline", "line1\nline2", `"line1\nline2"`},
	{"escape_carriage_return", "a\rb", `"a\rb"`},
	{"escape_tab", "a\tb", `"a\tb"`},
	{"escape_backspace", "a\bb", `"a\bb"`},
	{"escape_formfeed", "a\fb", `"a\fb"`},
	{"escape_control_x01", "\x01", `"\u0001"`},
	{"escape_control_x1f", "\x1f", `"\u001f"`},

	// ES2019 line/paragraph separators (Bundle-Spec divergence)
	{"escape_u2028", "a b", `"a b"`},
	{"escape_u2029", "a b", `"a b"`},

	// Non-ASCII raw UTF-8 (must pass through unescaped)
	{"utf8_german_umlaut", "Übermut", `"Übermut"`},
	{"utf8_thai", "ทดสอบ", `"ทดสอบ"`},

	// Arrays
	{"array_ints", []any{1, 2, 3}, "[1,2,3]"},
	{"array_mixed", []any{nil, true, "x", 42}, `[null,true,"x",42]`},

	// Objects: sorted keys (recursive, Unicode code-point order)
	{"object_one_key", map[string]any{"a": 1}, `{"a":1}`},
	{
		"object_keys_sorted_alphabetically",
		map[string]any{"b": 2, "a": 1, "c": 3},
		`{"a":1,"b":2,"c":3}`,
	},
	{
		"object_keys_sorted_codepoint",
		map[string]any{"Z": 1, "a": 2, "A": 3, "z": 4},
		// 'A' (0x41) < 'Z' (0x5a) < 'a' (0x61) < 'z' (0x7a)
		`{"A":3,"Z":1,"a":2,"z":4}`,
	},
	{
		"nested_object_keys_sorted",
		map[string]any{
			"outer": map[string]any{"z": 1, "a": 2},
		},
		`{"outer":{"a":2,"z":1}}`,
	},
	{
		"nested_array_of_objects",
		map[string]any{
			"items": []any{
				map[string]any{"id": 1, "name": "x"},
				map[string]any{"id": 2, "name": "y"},
			},
		},
		`{"items":[{"id":1,"name":"x"},{"id":2,"name":"y"}]}`,
	},

	// Manifest-shaped payload (Bundle-Spec §6.4 abbreviated, no optionals)
	// MUST byte-match the Python test_manifest.py
	// test_canonical_manifest_json_byte_exact_for_minimal_manifest expected value.
	{
		"manifest_minimal_no_optionals",
		map[string]any{
			"schema_version":          "1.0",
			"bundle_id":               "bnd-1745000000000-xk9m2p",
			"package_class":           "evidence",
			"created_at":              "2026-05-21T10:00:00.000Z",
			"product":                 "CKNF",
			"product_version":         "2.3.0",
			"installation_id":         "a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6",
			"license_reference":       "TSOL-****-****-Z9K2",
			"signing_key_fingerprint": "f1e2d3c4b5a697880123456789abcdef",
			"hash_algorithm":          "sha-256",
			"signature_algorithm":     "Ed25519",
			"timestamp_status":        "present",
			"artifact_count":          0,
			"artifacts":               []any{},
		},
		`{"artifact_count":0,"artifacts":[],"bundle_id":"bnd-1745000000000-xk9m2p","created_at":"2026-05-21T10:00:00.000Z","hash_algorithm":"sha-256","installation_id":"a3f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6","license_reference":"TSOL-****-****-Z9K2","package_class":"evidence","product":"CKNF","product_version":"2.3.0","schema_version":"1.0","signature_algorithm":"Ed25519","signing_key_fingerprint":"f1e2d3c4b5a697880123456789abcdef","timestamp_status":"present"}`,
	},
}

func TestCanonicalJSONByteExactGoldenVectors(t *testing.T) {
	for _, v := range canonicalGoldenVectors {
		t.Run(v.name, func(t *testing.T) {
			got, err := CanonicalJSONString(v.input)
			if err != nil {
				t.Fatalf("CanonicalJSONString error: %v", err)
			}
			if got != v.canonical {
				t.Fatalf(
					"byte mismatch:\n  got: %q\n want: %q",
					got, v.canonical,
				)
			}
		})
	}
}

func TestCanonicalJSON_RejectsNaN(t *testing.T) {
	_, err := CanonicalJSON(math.NaN())
	if err == nil {
		t.Fatal("expected error for NaN")
	}
	if !strings.Contains(err.Error(), "non-finite") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCanonicalJSON_RejectsPositiveInfinity(t *testing.T) {
	_, err := CanonicalJSON(math.Inf(1))
	if err == nil {
		t.Fatal("expected error for +Inf")
	}
}

func TestCanonicalJSON_RejectsNegativeInfinity(t *testing.T) {
	_, err := CanonicalJSON(math.Inf(-1))
	if err == nil {
		t.Fatal("expected error for -Inf")
	}
}

func TestCanonicalJSON_RejectsNonIntegerFloat(t *testing.T) {
	_, err := CanonicalJSON(3.14)
	if err == nil {
		t.Fatal("expected error for non-integer float")
	}
	if !strings.Contains(err.Error(), "non-integer float") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCanonicalJSON_AcceptsIntegerFloat(t *testing.T) {
	got, err := CanonicalJSONString(1.0)
	if err != nil {
		t.Fatalf("integer float should be accepted: %v", err)
	}
	if got != "1" {
		t.Fatalf("got %q, want %q", got, "1")
	}
}

func TestCanonicalJSON_AcceptsNegativeIntegerFloat(t *testing.T) {
	got, err := CanonicalJSONString(-3.0)
	if err != nil {
		t.Fatalf("negative integer float should be accepted: %v", err)
	}
	if got != "-3" {
		t.Fatalf("got %q, want %q", got, "-3")
	}
}

func TestCanonicalJSON_AcceptsZeroFloat(t *testing.T) {
	got, err := CanonicalJSONString(0.0)
	if err != nil {
		t.Fatalf("zero float should be accepted: %v", err)
	}
	if got != "0" {
		t.Fatalf("got %q, want %q", got, "0")
	}
}

func TestSHA256Hex_MatchesManualComputation(t *testing.T) {
	input := map[string]any{"a": 1, "b": "hello"}
	canonical, err := CanonicalJSON(input)
	if err != nil {
		t.Fatalf("CanonicalJSON: %v", err)
	}
	sum := sha256.Sum256(canonical)
	expected := hex.EncodeToString(sum[:])
	got, err := SHA256Hex(input)
	if err != nil {
		t.Fatalf("SHA256Hex: %v", err)
	}
	if got != expected {
		t.Fatalf("SHA256Hex returned %q, manual computation %q", got, expected)
	}
}

func TestSHA256Hex_IsLowercaseHex(t *testing.T) {
	got, err := SHA256Hex(map[string]any{"x": 1})
	if err != nil {
		t.Fatalf("SHA256Hex: %v", err)
	}
	if len(got) != 64 {
		t.Fatalf("hash length %d, want 64", len(got))
	}
	for _, c := range got {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			t.Fatalf("non-lowercase-hex char %q in %q", c, got)
		}
	}
}

func TestSHA256Hex_DeterministicForSameInput(t *testing.T) {
	input := map[string]any{
		"a": []any{1, 2, 3},
		"b": map[string]any{"nested": true},
	}
	a, _ := SHA256Hex(input)
	b, _ := SHA256Hex(input)
	if a != b {
		t.Fatalf("SHA256Hex differs across calls: %q vs %q", a, b)
	}
}

func TestSHA256Hex_DiffersForDifferentInputs(t *testing.T) {
	a, _ := SHA256Hex(map[string]any{"a": 1})
	b, _ := SHA256Hex(map[string]any{"a": 2})
	if a == b {
		t.Fatalf("SHA256Hex collision (or bug): %q", a)
	}
}

// Reflection-path coverage — Go users may pass concrete map types or
// nested slices that don't exactly match map[string]any / []any. The
// reflection round-trip must still produce canonical output.
func TestCanonicalJSON_ReflectionPath_StringIntMap(t *testing.T) {
	input := map[string]int{"a": 1, "b": 2}
	got, err := CanonicalJSONString(input)
	if err != nil {
		t.Fatalf("reflection path error: %v", err)
	}
	if got != `{"a":1,"b":2}` {
		t.Fatalf("reflection path produced %q", got)
	}
}

func TestCanonicalJSON_ReflectionPath_ConcreteSlice(t *testing.T) {
	input := []int{3, 1, 2}
	got, err := CanonicalJSONString(input)
	if err != nil {
		t.Fatalf("reflection path error: %v", err)
	}
	if got != `[3,1,2]` {
		t.Fatalf("reflection path produced %q", got)
	}
}
