// Copyright 2026 WBR IP & License Holding Pte. Ltd.
// SPDX-License-Identifier: Apache-2.0

// Stage C.2 — canonical_json byte-exact port of cknf.ntp_trust.canonical_json.
//
// Golden vectors were generated by running the actual Python source
// `from cknf.ntp_trust import canonical_json, sha256_of_canonical_json`
// inside the CKNF venv on 2026-05-19. If you add a vector here, regenerate
// the corresponding JSON and SHA-256 by running the same Python on the same
// input — DO NOT hand-edit either field.

package canonicaljson

import (
	"crypto/sha256"
	"encoding/hex"
	"testing"
)

type goldenVector struct {
	name string
	in   any
	want string // exact Python canonical_json output
	hash string // sha256_of_canonical_json(in)
}

var goldens = []goldenVector{
	{"null", nil, "null", "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b"},
	{"bool_true", true, "true", "b5bea41b6c623f7c09f1bf24dcae58ebab3c0cdd90ad966bc43a45b44867e12b"},
	{"bool_false", false, "false", "fcbcf165908dd18a9e49f7ff27810176db8e9f63b4352213741664245224f8aa"},
	{"int_zero", 0, "0", "5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9"},
	{"int_neg", -42, "-42", "fec80006df0542549b4cbaafb8987eee00bb49bca396eefe9ac8be5b5928e8f6"},
	{"int_big", 1234567890, "1234567890", "c775e7b757ede630cd0aa1113bd102661ab38829ca52a6422ab782862f268646"},
	{"empty_string", "", `""`, "12ae32cb1ec02d01eda3581b127c1fee3b0dc53572ed6baf239721a03d82e126"},
	{"ascii_string", "hello", `"hello"`, "5aa762ae383fbb727af3c7a36d4940a5b8c40a989452d2304fc958ff3f354e7a"},
	{"utf8_string", "Muenchen-Omega-naive", `"Muenchen-Omega-naive"`, "92d2098e89bf3d9fbaaac5f204741115e878652df64b8768e67e5e1fcc095bea"},
	{"iso_timestamp", "2026-05-19T10:00:00+00:00", `"2026-05-19T10:00:00+00:00"`, "695402c1abd47f0574f727a8afea04b292f4da2eecf4da2cc9cc01e1b5c9cd2e"},
	{"sha256_hex", "6ed8919ce20490a5e3ad8630a4fab69475297abd07db73918dd5f36fcfaeb11b", `"6ed8919ce20490a5e3ad8630a4fab69475297abd07db73918dd5f36fcfaeb11b"`, "d009d74b57948e07174490d8c6b0f8563e033070ae6c36c1d1fe48404666b79d"},
	{"empty_array", []any{}, "[]", "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"},
	{"mixed_array", []any{1, "two", 3, nil, true}, `[1,"two",3,null,true]`, "d1c3844311ccf71cfd8b9d544fa0e23d073ed7efa86edd4cc114c50369bc14f8"},
	{"empty_object", map[string]any{}, "{}", "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"},
	{"flat_object", map[string]any{"b": 2, "a": 1, "c": 3}, `{"a":1,"b":2,"c":3}`, "e6a3385fb77c287a712e7f406a451727f0625041823ecf23bea7ef39b2e39805"},
	{
		"clock_validation",
		map[string]any{
			"schema_version":     1,
			"status":             "ok",
			"servers":            []any{"cloudflare", "google", "pool"},
			"quorum":             3,
			"max_drift_ms":       115,
			"drift_threshold_ms": 1000,
			"drift_exceeded":     false,
		},
		`{"drift_exceeded":false,"drift_threshold_ms":1000,"max_drift_ms":115,"quorum":3,"schema_version":1,"servers":["cloudflare","google","pool"],"status":"ok"}`,
		"94c60be91a8feb72c9872d253cf7b30617438daa5d32cee5841d66d9c692fcc8",
	},
	{
		"nested",
		map[string]any{
			"outer": map[string]any{
				"inner":   []any{1, 2, map[string]any{"deep_a": "x", "deep_b": "y"}},
				"sibling": true,
			},
			"created_at": "2026-05-19T10:00:00+00:00",
		},
		`{"created_at":"2026-05-19T10:00:00+00:00","outer":{"inner":[1,2,{"deep_a":"x","deep_b":"y"}],"sibling":true}}`,
		"36d2b3bc1cafed78843e6c79ce577d1e8c26321f1f5b8d0f53bf4c37bb328fd1",
	},
	{
		"chars_lt_gt_amp",
		`<a href="x">x&y</a>`,
		`"<a href=\"x\">x&y</a>"`,
		"c0babf60f01835ac36586b8bc1c1b0a748b6940a232724f0d921199ed3374cb3",
	},
}

func TestMarshal_GoldenVectors(t *testing.T) {
	for _, g := range goldens {
		t.Run(g.name, func(t *testing.T) {
			got, err := MarshalString(g.in)
			if err != nil {
				t.Fatalf("Marshal: %v", err)
			}
			if got != g.want {
				t.Errorf("byte-exact mismatch\n  want: %q\n  got:  %q", g.want, got)
			}
		})
	}
}

func TestSHA256Hex_GoldenVectors(t *testing.T) {
	for _, g := range goldens {
		t.Run(g.name, func(t *testing.T) {
			h, err := SHA256Hex(g.in)
			if err != nil {
				t.Fatalf("SHA256Hex: %v", err)
			}
			if h != g.hash {
				t.Errorf("hash mismatch\n  want: %s\n  got:  %s", g.hash, h)
			}
			expectedSum := sha256.Sum256([]byte(g.want))
			expectedHex := hex.EncodeToString(expectedSum[:])
			if expectedHex != g.hash {
				t.Errorf("test vector is self-inconsistent: hash %s does not match SHA-256 of %q (= %s)",
					g.hash, g.want, expectedHex)
			}
		})
	}
}

func TestMarshal_RejectsFloat32(t *testing.T) {
	if _, err := Marshal(float32(1.5)); err == nil {
		t.Error("expected error on float32 input")
	}
}

func TestMarshal_RejectsFloat64(t *testing.T) {
	if _, err := Marshal(float64(1.5)); err == nil {
		t.Error("expected error on float64 input")
	}
}

func TestMarshal_RejectsFloatInMap(t *testing.T) {
	in := map[string]any{"x": 1.0}
	if _, err := Marshal(in); err == nil {
		t.Error("expected error on map containing float")
	}
}

func TestMarshal_TypedStruct(t *testing.T) {
	type kv struct {
		B int `json:"b"`
		A int `json:"a"`
	}
	got, err := MarshalString(kv{B: 2, A: 1})
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	want := `{"a":1,"b":2}`
	if got != want {
		t.Errorf("typed struct\n  want: %s\n  got:  %s", want, got)
	}
}

func TestMarshal_DeterministicAcrossRuns(t *testing.T) {
	in := map[string]any{
		"z": []any{"end"},
		"a": 1,
		"m": map[string]any{"y": 2, "x": 1},
	}
	first, err := MarshalString(in)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	for i := 0; i < 100; i++ {
		got, err := MarshalString(in)
		if err != nil {
			t.Fatalf("Marshal iter %d: %v", i, err)
		}
		if got != first {
			t.Fatalf("non-deterministic output at iter %d:\n  first: %q\n  got:   %q",
				i, first, got)
		}
	}
}
